
name: Manual Screenshot Bot

on:
  push:
    branches: [screenshots]
  workflow_dispatch:
    inputs:

jobs:
  screenshots:
    name: 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Planet Farms
        run: |
          sudo apt install tor
          sudo npm install -g @treehouses/cli
          #export gitter_channel="${{ secrets.CHANNEL }}"
          sudo treehouses tor add 22
          sudo treehouses tor add 3000
          sudo treehouses tor
          sudo treehouses tor notice now
          sudo treehouses sshkey github adduser dogi
          echo "REACT_APP_API_BASE_URL=https://api.planetfarms.io" > .env
          echo "REACT_APP_CDN_BASE_URL=https://cdn.planetfarms.io" >> .env
          echo "cat .env"
          cat .env
          echo "farm: npm i"
          npm i
          echo "starting planetfarms"
          npm start &
          sleep 20
      - name: Screenshot Login
        uses: swinton/screenshot-website@v1.x
        with:
          source: http://localhost:3000/login
          destination: /screenshots
          full-page: true
      - name: Screenshot Register
        uses: swinton/screenshot-website@v1.x
        with:
          source: http://localhost:3000/register
          destination: /screenshots
          full-page: true
      - name: Get Token
        run: |
          token=$(curl -s -X POST https://api.planetfarms.io/api/users/login -d '{"username": "${{ secrets.LOGIN }}", "password": "${{ secrets.PASSWORD }}"}' -H 'Content-Type: application/json' | sed -e 's/{"token":"//' | sed -e 's/"}//')
          echo $token
          echo $token > look
          echo "TOKEN=$token" >> $GITHUB_ENV
      - name: Screenshot News
        uses: swinton/screenshot-website@v1.x
        with:
          source: http://localhost:3000/community-page-news
          destination: /screenshots
          full-page: true
          headers: '{Authorization: "Bearer ${{ env.TOKEN }}"}'
      - name: Sleep
        run: |
          #echo "5min countdown"
          #sleep 60
          #echo "4min countdown"
          #sleep 60
          #echo "5min countdown"
          #sleep 60
          #echo "3min countdown"
          #sleep 60
          #echo "2min countdown"
          #sleep 60
          echo "1min countdown"
          sleep 60
          echo "stop"
