
name: Manual Screenshot Bot

on:
  push:
    branches: [screenshots]
  workflow_dispatch:
    inputs:

jobs:
  screenshots:
    name: 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Planet Farms
        run: |
          sudo apt install tor #openssh-server
          sudo npm install -g @treehouses/cli
          #export gitter_channel="${{ secrets.CHANNEL }}"
          sudo treehouses tor add 22
          sudo treehouses tor add 3000
          sudo treehouses tor add 5000
          #sudo treehouses tor add 5432
          sudo treehouses tor add 8080
          sudo treehouses tor add 8081
          sudo treehouses tor
          sudo treehouses tor notice now
          sudo treehouses sshkey github adduser dogi
          docker-compose up -d
          cp .env.example .env
          echo "cat .env"
          cat .env
          cd api
          cp .env.example .env
          echo "cat api/.env"
          cat .env
          echo "api: npm i"
          npm i
          echo "api: npx sequelize-cli db:migrate"
          npx sequelize-cli db:migrate
          cd ..
          echo "farm: npm i"
          npm i
          echo "starting planetfarms"
          npm run dev &
          echo "5min countdown"
          sleep 60
          echo "4min countdown"
          sleep 60
          echo "5min countdown"
          sleep 60
          echo "3min countdown"
          sleep 60
          echo "2min countdown"
          sleep 60
          echo "1min countdown"
          sleep 60
          echo "stop"
